// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatScrollController from "./chat_scroll_controller"
application.register("chat-scroll", ChatScrollController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PieChartController from "./pie_chart_controller"
application.register("pie-chart", PieChartController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)

import SearchFormController from "./search_form_controller"
application.register("search-form", SearchFormController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import ThreejsController from "./threejs_controller"
application.register("threejs", ThreejsController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import TrixController from "./trix_controller"
application.register("trix", TrixController)
