default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

sqlite: &sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: otaku_sen_development
  cache:
    <<: *default
    database: otaku_sen_development_cache
    migrations_paths: db/cache_migrate
  cable:
    <<: *default
    database: otaku_sen_development_cable
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: otaku_sen_test

production:
  primary: &primary_production
    <<: *default
    database: otaku_sen_production
    username: otaku_sen
    password: <%= ENV["OTAKU_SEN_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: otaku_sen_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: otaku_sen_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: otaku_sen_production_cable
    migrations_paths: db/cable_migrate
